version: '3'

services:
  monitoring:
    image: nicolargo/glances:latest-full
    container_name: glances
    restart: unless-stopped
    ports: 
      - "${HTTP_PORT}:61208"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - "GLANCES_OPT=${GLANCES_OPTS}"
    # For nvidia GPUs
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${GPU_DRIVER}
              count: ${GPU_THREADS}
              capabilities: [gpu]
    healthcheck:
      test: ["CMD-SHELL", "curl -fail http://localhost:61208 || exit 1"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
